
export default new Map([
["src/content/projets/interventions-poetiques/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojets%2Finterventions-poetiques%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projets/petites-mains/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojets%2Fpetites-mains%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/art-public/refus-misere/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fart-public%2Frefus-misere%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/livres-artiste/mediation-beaucoup-obscurite/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flivres-artiste%2Fmediation-beaucoup-obscurite%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/expovente-arprim/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fexpovente-arprim%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/installation-recit-choral/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Finstallation-recit-choral%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/manifastation-jeus/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmanifastation-jeus%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/maskipeche-boucherville/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmaskipeche-boucherville%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/marginale/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmarginale%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/maskipeche-presse-papier/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmaskipeche-presse-papier%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/fournache-2024/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Ffournache-2024%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/se-raconter-par-poesie/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Fse-raconter-par-poesie%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/racines-plurielles/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Fracines-plurielles%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/mediation-arprim-fev2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Fmediation-arprim-fev2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/maskipeche-lasalle/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmaskipeche-lasalle%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/expositions/maskipeche-st-bruno/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fexpositions%2Fmaskipeche-st-bruno%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/mediation-boucherville/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Fmediation-boucherville%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/mediations/zocalo-atelier-poesie-aut2022/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmediations%2Fzocalo-atelier-poesie-aut2022%2Findex.mdx&astroContentModuleFlag=true")]]);
		