
import __ASTRO_IMAGE_IMPORT_8XHU8 from "images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flivres-artiste%2Fmediation-beaucoup-obscurite%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZihK4O from "images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmediations%2Fbeaucoup-obscurite-quelques-eclats%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2ngd8P from "images/calq_logo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fpetites-mains%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1qpYlH from "images/culture_monteregie_couleur_Modif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fpetites-mains%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z22fvIY from "images/calq_logo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fresidence-ig-culture-monteregie%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1YQN9u from "images/culture_monteregie_couleur_Modif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fresidence-ig-culture-monteregie%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1iCNHg from "images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmediations%2Ftable-ronde-lancement-livre%2Findex.md";
export default new Map([["images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flivres-artiste%2Fmediation-beaucoup-obscurite%2Findex.md", __ASTRO_IMAGE_IMPORT_8XHU8], ["images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmediations%2Fbeaucoup-obscurite-quelques-eclats%2Findex.md", __ASTRO_IMAGE_IMPORT_ZihK4O], ["images/calq_logo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fpetites-mains%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2ngd8P], ["images/culture_monteregie_couleur_Modif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fpetites-mains%2Findex.md", __ASTRO_IMAGE_IMPORT_1qpYlH], ["images/calq_logo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fresidence-ig-culture-monteregie%2Findex.md", __ASTRO_IMAGE_IMPORT_Z22fvIY], ["images/culture_monteregie_couleur_Modif.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojets%2Fresidence-ig-culture-monteregie%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1YQN9u], ["images/entente-development-culturel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmediations%2Ftable-ronde-lancement-livre%2Findex.md", __ASTRO_IMAGE_IMPORT_1iCNHg]]);
		